export class ReportsData {
    public EmployeeCode: string;
    public EmployeeName: string;
    public ProgramManagerName: string;
    public ReportingManagerName: string;
    public LeadName: string;
    public RoleName: string;
    public DesignationName: string;
    public Description: string;
    public Experience: string;
    public JoinDate: string;
    public SkillCode: string;
    public PrimarySkill: string;
    public SecondarySkill: string;
    public GradeName: string;
    public ClientName: string;
    public ClientCode: string;
    public ProjectName: string;
    public IsBillable: boolean;
    public IsCritical: boolean;
    public ClientBillingPercentage: number;
    public Allocationpercentage: number;
    public InternalBillingPercentage: number;
    public InternalBillingRoleCode: string;
    public ClientBillingRoleCode: string
    public FromDate: string;
    public ToDate: string;
    public Technology: string;
    public Lead: string;
    public AadharNumber: string;
    public EmployeeType: string;
    public CareerBreak: number;
    public ExperienceExcludingCareerBreak: string;
    public IsBillableForExcel: string;
    public IsCriticalForExcel: string;
}