-- Table: public.Cycles

-- DROP TABLE public."Cycles";

CREATE TABLE public."Cycles"
(
    "CycleId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(50) COLLATE pg_catalog."default",
    "FromMonth" integer NOT NULL,
    "ToMonth" integer NOT NULL,
    "CreatedDate" timestamp with time zone,
    "ModifiedDate" timestamp with time zone,
    "SystemInfo" character varying(50) COLLATE pg_catalog."default",
    "IsActive" boolean,
    "CreatedBy" character varying(100) COLLATE pg_catalog."default",
    "ModifiedBy" character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT "Cycles_pkey" PRIMARY KEY ("CycleId")
);