-- Table: public.AssociateExitActivity

-- DROP TABLE IF EXISTS public."AssociateExitActivity";

CREATE TABLE IF NOT EXISTS public."AssociateAbscond"
(
    "AssociateAbscondId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "AssociateId" integer NOT NULL,
	"AbsentFromDate" timestamp with time zone,
    "AbsentToDate" timestamp with time zone,
    "IsAbscond" boolean NOT NULL,
    "StatusId" integer NOT NULL,
    "TLId" integer,
    "RemarksByTL" text COLLATE pg_catalog."default",
    "HRAId" integer,
    "RemarksByHRA" text COLLATE pg_catalog."default",
	"HRMId" integer,
    "RemarksByHRM" text COLLATE pg_catalog."default",
	"IsActive" boolean,
    "CreatedBy" character varying(100) COLLATE pg_catalog."default",
    "CreatedDate" timestamp with time zone,
    "ModifiedBy" character varying(100) COLLATE pg_catalog."default",
    "ModifiedDate" timestamp with time zone,
    CONSTRAINT "PK_AssociateAbscond" PRIMARY KEY ("AssociateAbscondId")
)

