ALTER TABLE public."FinancialYear"
ADD COLUMN "IsActive" BOOLEAN NOT NULL;

ALTER TABLE public."FinancialYear"
ADD COLUMN "CreatedDate" TIMESTAMP;

ALTER TABLE public."FinancialYear"
ADD COLUMN "ModifiedDate" TIMESTAMP;

ALTER TABLE public."FinancialYear"
ADD COLUMN "CreatedBy" VARCHAR(100);

ALTER TABLE public."FinancialYear"
ADD COLUMN "ModifiedBy" VARCHAR(100);

---------------------------------------------------------------------------------------
-- public."RoleType" definition
-- Drop table
-- DROP TABLE public."RoleType";

CREATE TABLE public."RoleType" (
    "RoleTypeId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoleTypeName" varchar(100) NOT NULL,
    "RoleTypeDescription" varchar(500) NULL,
    "FinancialYearId" integer NOT NULL,
    "DepartmentId" integer NOT NULL,
    "IsDeliveryDepartment" BOOLEAN NOT NULL,
    "CreatedDate" timestamptz NULL,
    "ModifiedDate" timestamptz NULL,
    "CreatedBy" varchar(100) NULL,
    "ModifiedBy" varchar(100) NULL,
    CONSTRAINT "PK_RoleType" PRIMARY KEY ("RoleTypeId"),
    CONSTRAINT "FK_RoleType_FinancialYear_FinancialYearId"
    FOREIGN KEY ("FinancialYearId") REFERENCES public."FinancialYear" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT,
    CONSTRAINT "FK_RoleType_Department_DepartmentId"
    FOREIGN KEY ("DepartmentId") REFERENCES public."Department" ("DepartmentId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT
);

-- Index: IX_RoleType_FinancialYearId_DepartmentId
-- DROP INDEX IF EXISTS public."IX_RoleType_FinancialYearId_DepartmentId";

CREATE INDEX IF NOT EXISTS "IX_RoleType_FinancialYearId_DepartmentId"
    ON public."RoleType" USING btree
    ("FinancialYearId","DepartmentId" ASC NULLS LAST)
    TABLESPACE pg_default;
--------------------------------------------------------------------------------------

-- Table: public.GradeRoleType
-- DROP TABLE IF EXISTS public."GradeRoleType";

CREATE TABLE IF NOT EXISTS public."GradeRoleType"
(
    "GradeRoleTypeId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "RoleTypeId" integer NOT NULL,
    "GradeId" integer NOT NULL,
    "CreatedDate" timestamp with time zone,
    "ModifiedDate" timestamp with time zone,
    "CreatedBy" character varying(100) COLLATE pg_catalog."default",
    "ModifiedBy" character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT "PK_GradeRoleType" PRIMARY KEY ("GradeRoleTypeId"),
    CONSTRAINT "FK_GradeRoleType_RoleType_RoleTypeId" FOREIGN KEY ("RoleTypeId")
        REFERENCES public."RoleType" ("RoleTypeId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_GradeRoleType_Grade_GradeId" FOREIGN KEY ("GradeId")
        REFERENCES public."Grade" ("GradeId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)
-- Index: IX_GradeRoleType_RoleTypeId_GradeId
-- DROP INDEX IF EXISTS public."IX_GradeRoleType_RoleTypeId_GradeId";
CREATE INDEX IF NOT EXISTS "IX_GradeRoleType_RoleTypeId_GradeId"
    ON public."GradeRoleType" USING btree
    ("RoleTypeId","GradeId" ASC NULLS LAST)
    TABLESPACE pg_default;