-- Table: public.DepartmentDL

-- DROP TABLE IF EXISTS public."DepartmentDL";

CREATE TABLE IF NOT EXISTS public."DepartmentDL"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "DepartmentId" integer NOT NULL,
    "DLEmailAdress" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_DepartmentDL" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;
