-- public."ExitType" definition

-- Drop table

-- DROP TABLE public."ExitType";

CREATE TABLE public."ExitType" (
	"ExitTypeId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"CreatedDate" timestamptz NULL,
	"ModifiedDate" timestamptz NULL,
	"SystemInfo" varchar(50) NULL,
	"IsActive" bool NULL,
	"CreatedBy" varchar(100) NULL,
	"ModifiedBy" varchar(100) NULL,
	"Description" varchar(256) NOT NULL,
	CONSTRAINT "PK_ExitType" PRIMARY KEY ("ExitTypeId")
);