-- public."Reason" definition

-- Drop table

-- DROP TABLE public."Reason";

CREATE TABLE public."Reason" (
	"ReasonId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"CreatedDate" timestamptz NULL,
	"ModifiedDate" timestamptz NULL,
	"SystemInfo" varchar(50) NULL,
	"IsActive" bool NULL,
	"CreatedBy" varchar(100) NULL,
	"ModifiedBy" varchar(100) NULL,
	"ReasonCode" varchar(50) NOT NULL,
	"Description" varchar(256) NOT NULL,
	"ReasonTypeId" int4 NOT NULL,
	CONSTRAINT "PK_Reason" PRIMARY KEY ("ReasonId")
);
CREATE INDEX "IX_Reason_ReasonTypeId" ON public."Reason" USING btree ("ReasonTypeId");


-- public."Reason" foreign keys

ALTER TABLE public."Reason" ADD CONSTRAINT "FK_Reason_ReasonType_ReasonTypeId" FOREIGN KEY ("ReasonTypeId") REFERENCES public."ReasonType"("ReasonTypeId") ON DELETE RESTRICT;