-- public."AssociateExitAnalysis" definition

-- Drop table

-- DROP TABLE public."AssociateExitAnalysis";

CREATE TABLE public."AssociateExitAnalysis" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"CreatedDate" timestamptz NULL,
	"ModifiedDate" timestamptz NULL,
	"SystemInfo" varchar(50) NULL,
	"IsActive" bool NULL,
	"CreatedBy" varchar(100) NULL,
	"ModifiedBy" varchar(100) NULL,
	"AssociateExitId" int4 NOT NULL,
	"RootCause" text NULL,
	"ActionItem" text NULL,
	"Responsibility" text NULL,
	"TagretDate" timestamptz NULL,
	"ActualDate" timestamptz NULL,
	"Remarks" text NULL,
	"StatusId" int4 NOT NULL,
	CONSTRAINT "PK_AssociateExitAnalysis" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "IX_AssociateExitAnalysis_AssociateExitId" ON public."AssociateExitAnalysis" USING btree ("AssociateExitId");


-- public."AssociateExitAnalysis" foreign keys

ALTER TABLE public."AssociateExitAnalysis" ADD CONSTRAINT "FK_AssociateExitAnalysis_AssociateExit_AssociateExitId" FOREIGN KEY ("AssociateExitId") REFERENCES public."AssociateExit"("AssociateExitId") ON DELETE CASCADE;