-- public."AssociateExit" definition

-- Drop table

-- DROP TABLE public."AssociateExit";

CREATE TABLE public."AssociateExit" (
	"AssociateExitId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"CreatedDate" timestamptz NULL,
	"ModifiedDate" timestamptz NULL,
	"SystemInfo" varchar(50) NULL,
	"IsActive" bool NULL,
	"CreatedBy" varchar(100) NULL,
	"ModifiedBy" varchar(100) NULL,
	"EmployeeId" int4 NOT NULL,
	"ExitTypeId" int4 NOT NULL,
	"ActualExitReasonId" int4 NULL,
	"ActualExitReasonDetail" varchar(256) NULL,
	"ExitReasonId" int4 NULL,
	"ExitReasonDetail" varchar(256) NULL,
	"ResignationRecomendation" varchar(256) NULL,
	"CalculatedExitDate" timestamptz NULL,
	"ActualExitDate" timestamptz NULL,
	"RehireEligibility" bool NULL,
	"RehireEligibilityDetail" text NULL,
	"ResignationWithdrawn" bool NOT NULL,
	"WithdrawReason" text NULL,
	"WithdrawRemarks" text NULL,
	"TransitionRequired" bool NULL,
	"ImpactOnClientDelivery" bool NULL,
	"ImpactOnClientDeliveryDetail" varchar(256) NULL,
	"Tenure" numeric NULL,
	"Retained" bool NULL,
	"RetainedDetail" varchar(256) NULL,
	"LegalExit" bool NOT NULL,
	"StatusId" int4 NOT NULL,
	"ProjectId" int4 NULL,
	"ResignationDate" timestamptz NULL,
	"ExitDate" timestamptz NULL,
	"AssociateRemarks" varchar(256) NULL,
	"AbscondedFromDate" timestamptz NULL,
	"AbscondedToDate" timestamptz NULL,
	"CauseDetails" varchar(256) NULL,
	"AbscondEvidence" varchar(256) NULL,
	CONSTRAINT "PK_AssociateExit" PRIMARY KEY ("AssociateExitId")
);