-- public."TransitionPlanDetail" definition

-- Drop table

-- DROP TABLE public."TransitionPlanDetail";

CREATE TABLE public."TransitionPlanDetail" (
	"TransitionPlanDetailId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"CreatedDate" timestamptz NULL,
	"ModifiedDate" timestamptz NULL,
	"SystemInfo" varchar(50) NULL,
	"IsActive" bool NULL,
	"CreatedBy" varchar(100) NULL,
	"ModifiedBy" varchar(100) NULL,
	"TransitionPlanId" int4 NOT NULL,
	"ActivityId" int4 NOT NULL,
	"StartDate" timestamptz NULL,
	"EndDate" timestamptz NULL,
	"Remarks" text NULL,
	"Status" varchar(256) NULL,
	"ActivityDescription" text NULL,
	CONSTRAINT "PK_TransitionPlanDetail" PRIMARY KEY ("TransitionPlanDetailId")
);
CREATE INDEX "IX_TransitionPlanDetail_TransitionPlanId" ON public."TransitionPlanDetail" USING btree ("TransitionPlanId");


-- public."TransitionPlanDetail" foreign keys

ALTER TABLE public."TransitionPlanDetail" ADD CONSTRAINT "FK_TransitionPlanDetail_TransitionPlan_TransitionPlanId" FOREIGN KEY ("TransitionPlanId") REFERENCES public."TransitionPlan"("TransitionPlanId") ON DELETE CASCADE;