-- Table: public.AssociateExitRevokeWorkflow

-- DROP TABLE IF EXISTS public."AssociateExitRevokeWorkflow";

CREATE TABLE IF NOT EXISTS public."AssociateExitRevokeWorkflow"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "AssociateExitId" integer NOT NULL,
	"RevokeStatusId" integer NOT NULL,
    "RevokeComment" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    "IsActive" boolean,
    "CreatedBy" character varying(100) COLLATE pg_catalog."default",
	"CreatedDate" timestamp with time zone,
    "ModifiedBy" character varying(100) COLLATE pg_catalog."default",
    "ModifiedDate" timestamp with time zone,
    CONSTRAINT "PK_AssociateExitRevokeWorkflow" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;
