-- Need to execute the below command in Employee Database

-- Table: public.AssociateExitInterviewReview

-- DROP TABLE public."AssociateExitInterviewReview";

CREATE TABLE public."AssociateExitInterviewReview"
(
    "AssociateExitInterviewReviewId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CreatedDate" timestamp with time zone,
    "ModifiedDate" timestamp with time zone,
    "SystemInfo" character varying(50) COLLATE pg_catalog."default",
    "IsActive" boolean,
    "CreatedBy" character varying(100) COLLATE pg_catalog."default",
    "ModifiedBy" character varying(100) COLLATE pg_catalog."default",
    "AssociateExitInterviewId" integer NOT NULL,   
    "ShowInitialRemarks" boolean NOT NULL,   
    "FinalRemarks" character varying(5000) COLLATE pg_catalog."default",
    CONSTRAINT "PK_AssociateExitInterviewReview" PRIMARY KEY ("AssociateExitInterviewReviewId"),
    CONSTRAINT "FK_AssociateExitInterview_AssociateExitInterviewReview_Id" FOREIGN KEY ("AssociateExitInterviewId")
        REFERENCES public."AssociateExitInterview" ("AssociateExitInterviewId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;